project_id = "ilknzgupnswyeynwpovj"

[functions.manage-users]
verify_jwt = false

[functions.validate-keyword]
verify_jwt = false

[functions.radar-rastrear]
verify_jwt = false

[functions.radar-cron]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.check-video-status]
verify_jwt = false
